main:
  # - identifier: blog
  #   name: Blog
  #   weight: 4
  #   params:
  #     icon:
  #       vendor: fas
  #       name: blog
  - identifier: whatis
    name: What is...
    weight: 10
    params:
      icon:
        vendor: far
        name: circle-question

  - identifier: sfl
    name: ARRL South Florida Section
    parent: links
    weight: 11
    url: http://www.arrl.org/sections/view/southern-florida
    params:
      icon:
        vendor: fas
        name: arrow-up-right-from-square

  - identifier: ocw
    name: Osceola County Weather
    parent: links
    weight: 13
    url: https://forecast.weather.gov/MapClick.php?lat=28.068126019000033&lon=-81.14519673199999#.XMmu9y-ZPOQ
    params:
      icon:
        vendor: fas
        name: arrow-up-right-from-square

  - identifier: dues
    name: Pay dues
    weight: 100
    url: https://www.paypal.com/ncp/payment/EEN58Z96DDWAA
    params:
      icon:
        name: paypal

  - identifier: donate
    name: Donate
    weight: 105
    url: https://www.paypal.com/donate/?hosted_button_id=G4VFG9VPEL3YA
    params:
      icon:
        name: paypal
