# description: Osceola Amateur Radio Emergency Service

hb:
  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.
  full_width: true # when true, the layout takes full width globally.
  header:
    brand: Osceola ARES # the brand name, leave it empty to use site's title.
    git_org:
      name: osceolaares
      service: github
    # logo_bg: '#712cf9' # logo background color, used by logo with transparent background.
    logo_bg: '#ffffff'
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      github: osceolaares
      bluesky: osceolacountyares.org
      rss: true
  footer:
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      _color: false # when false, remove the color of social icons.
      github: osceolaares
      bluesky: osceolacountyares.org
      rss: true
    powered_by: false
  blog:
    list_cols_md: 2
    list_cols_lg: 3
    toc:
      position: end
    social_share_buttons:
      alignment: center
      media:
        - bluesky
        - twitter
        - facebook
        - linkedin
    sidebar:
      sticky: false # set it to false to not stick the sidebar.
      width: .35 # the width of sidebar.
      position: start # the sidebar position: start (left) or end (right).
      profile:
        title: Osceola ARES
        avatar_size: 120
        company: KG4EOC
        location: Osceola County, FL
        socials:
          _color: false # when false, remove the color of social icons.
          github: osceolaares
          bluesky: osceolacountyares.org
          rss: true
      posts:
        recent_count: 0 # the number of recent posts.
        featured_count: 0 # the number of featured posts.
        style: pills # pills, tabs or underline.
        list_style: slide # slide or vertical.
      taxonomies:
        count: true # whether to show the number of posts associated to the item.
        limit: 10 # the maximum number of the item.
        style: pills # pills, tabs or underline.
        separate: false # whether to separate into multiple sections.
        authors:
          disable: true # whether to disable this taxonomy.
          weight: 1 # the weight of this taxonomy, lower gets higher priority.
          count: false # override the global count setting.
          limit: 5 # override the global limit setting.
        series:
          disable: true
          weight: 2
        tags:
          disable: false
          weight: 3
          limit: 20
          # title: Popular Tags # override the title.
        categories:
          disable: false
          weight: 4
    paginate: 12 # paginate.
    post_thumbnail_placeholder: Osceola ARES # the text of thumbnail placeholder, default to site title.
    post_thumbnail_default: images/logo.png
    # post_thumbnail: false # whether to show the thumbnails.
    # post_date_format: ":date_long" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      # taxonomies: false # remove the taxonomies stat from the homepage.
      featured_posts: 5 # the number of the featured posts, 0 means disabled.
      pinned_posts_position: "list"
      main_sections: # leave it empty to include all regular pages.
        # - docs
        - blog
        - news
    giscus:
      repo: osceolaares/osceola-ares-site
      repo_id: R_kgDOL0Mzpg
      category_id: DIC_kwDOL0Mzps4Ce_oD
  docs:
    giscus:
      repo: osceolaares/osceola-ares-site
      repo_id: R_kgDOL0Mzpg
      category_id: DIC_kwDOL0Mzps4Ce_oD
    social_share_buttons:
      alignment: center
      media:
        - bluesky
        - twitter
        - facebook
        - linkedin
  content_panel:
    repo:
      service: github
      repo: osceolaares/osceola-ares-site
      branch: main
  gallery:
    date_sort_order: asc
    highlight_images_count: 10
    highlight_images_recursive: false
    paginate: 12
    thumbnail_size: "x640"
  google_fonts:
    families:
      - name: Oswald
  styles:
    hb_gallery_album_item_border_radius: 15px
    hb_gallery_album_item_gap: 10px
  back_to_top:
    icon_name: hurricane
seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.png # use logo as favicon.

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: '#712cf9'
    theme_color: '#712cf9'
    short_name: 'Osceola ARES'

# see https://hugomods.com/search/configurations/.
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  shortcut_search: ["/"]

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 4
    # change the order of sidebar modules.
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2
