queue_rules:
  - name: default
    batch_size: 5

pull_request_rules:
  - name: Queue Renovate PRs
    conditions:
      - author=renovate[bot]
      - check-success=terraform
      - check-success=AWS Amplify Console Web Preview
      - -draft
    actions:
      queue:
        name: default
      merge:
        method: squash
      delete_head_branch: {}

  - name: Queue on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=terraform
      - check-success=AWS Amplify Console Web Preview
      - -draft
    actions:
      queue:
        name: default
      merge:
        method: squash
      delete_head_branch: {}

  - name: Queue admin PRs
    conditions:
      - author=jbouse
      - check-success=terraform
      - check-success=AWS Amplify Console Web Preview
      - -draft
    actions:
      queue:
        name: default
      merge:
        method: squash
      delete_head_branch: {}

  - name: Pre-Approved PR commitors
    # This rule is for pre-approved commitors like Renovate, Dependabot, and jbouse.
    # It automatically approves PRs created by these commitors.
    conditions:
      - or:
        - author=renovate[bot]
        - author=dependabot[bot]
        - author=jbouse
    actions:
      review:
        type: APPROVE
        message: Automatically approving