queue_rules:
  - name: default
    batch_size: 5

pull_request_rules:
  - name: Queue Renovate PRs
    conditions:
      - author=renovate[bot]
      - check-success=terraform
      - check-success=AWS Amplify Console Web Preview
      - -draft
      # Optionally, require a label for more granular control:
      # - label=automerge
    actions:
      queue:
        name: default

  - name: Queue on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=terraform
      - check-success=AWS Amplify Console Web Preview
      - -draft
    actions:
      queue:
        name: default

  - name: Queue admin PRs
    conditions:
      - author=jbouse
      - check-success=terraform
      - check-success=AWS Amplify Console Web Preview
      - -draft
    actions:
      queue:
        name: default