queue_rules:
  - name: default
    batch_size: 5
    batch_max_wait_time: 30 minutes
    queue_conditions:
      - check-success=terraform
      - check-success=AWS Amplify Console Web Preview
      - -draft

pull_request_rules:
  - name: Queue Pre-Approved PRs
    conditions:
      - author~=^(renovate\[bot\]|dependabot\[bot\]|jbouse)$
    actions:
      queue:
        name: default
      merge:
        method: squash
      delete_head_branch: {}

  - name: Queue on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
      merge:
        method: squash
      delete_head_branch: {}


  - name: Pre-Approved PR commitors
    # This rule is for pre-approved commitors like Renovate, Dependabot, and jbouse.
    # It automatically approves PRs created by these commitors.
    conditions:
      - or:
        - author=renovate[bot]
        - author=dependabot[bot]
        - author=jbouse
    actions:
      review:
        type: APPROVE
        message: Automatically approving